// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwhQY1I1RAFpzwNh38MnWvWiXhwRjH8k8',
    appId: '1:594842383243:web:c916fa824b3d8added358e',
    messagingSenderId: '594842383243',
    projectId: 'school-saas-7dd7f',
    authDomain: 'school-saas-7dd7f.firebaseapp.com',
    storageBucket: 'school-saas-7dd7f.firebasestorage.app',
    measurementId: 'G-VKGZS1T3PL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf-8Fn4p16BFqY38iu3UqPHN90_-RzT6Q',
    appId: '1:594842383243:android:875f25856e0fe66eed358e',
    messagingSenderId: '594842383243',
    projectId: 'school-saas-7dd7f',
    storageBucket: 'school-saas-7dd7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3X_ZboSV5wRH4DQgg6Bg8o-h-0EgFemg',
    appId: '1:594842383243:ios:0e9dbb975940e9d8ed358e',
    messagingSenderId: '594842383243',
    projectId: 'school-saas-7dd7f',
    storageBucket: 'school-saas-7dd7f.firebasestorage.app',
    iosBundleId: 'com.student.parent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3X_ZboSV5wRH4DQgg6Bg8o-h-0EgFemg',
    appId: '1:594842383243:ios:0e9dbb975940e9d8ed358e',
    messagingSenderId: '594842383243',
    projectId: 'school-saas-7dd7f',
    storageBucket: 'school-saas-7dd7f.firebasestorage.app',
    iosBundleId: 'com.student.parent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwhQY1I1RAFpzwNh38MnWvWiXhwRjH8k8',
    appId: '1:594842383243:web:4f55b9f76764c48ded358e',
    messagingSenderId: '594842383243',
    projectId: 'school-saas-7dd7f',
    authDomain: 'school-saas-7dd7f.firebaseapp.com',
    storageBucket: 'school-saas-7dd7f.firebasestorage.app',
    measurementId: 'G-LQ7GH6R2CX',
  );
}
